# -*- coding: utf-8 -*-
"""ccn deeplearing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h1mvuFa5ANcChnT0fwx9sepGnUQyrdfp
"""

import pandas as pd

import seaborn as sns

import matplotlib.pyplot as plt

import numpy as np

df=pd.read_csv("/content/sample_data/Message Group - Product.csv .new.csv")

df.head()

df.info()

df.describe()

df.tail()

from sklearn.model_selection import train_test_split

df.columns

X = df["S.No"]
y = df["SellPrice"]

from sklearn.svm import SVR
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
svr_model = SVR(kernel='linear')
svr_model.fit(X_train.values.reshape(-1, 1), y_train)
score = svr_model.score(X_test.values.reshape(-1, 1), y_test)
print(f"SVR model score: {score}")

